CREATE TABLE DEPART(

DEPT_NO NUMBER(2),

DNOMBRE VARCHAR2(50),

LOC VARCHAR2(50),

CONSTRAINT PK_DEPT_NO PRIMARY KEY (DEPT_NO),
CONSTRAINT LOCALIDAD CHECK(LOC IN('SEVILLA','MADRID','BARCELONA','BILBAO')),
CONSTRAINT DNOMBRE_MAYUS CHECK(DNOMBRE = UPPER(DNOMBRE)),
CONSTRAINT ENTRE_DEPT CHECK (DEPT_NO BETWEEN 0 AND 99) 
);

/*/////////////////////////////////////////////////////////////////////////////////*/


CREATE TABLE EMPLE (

EMP_NO NUMBER(4),

APELLIDO VARCHAR2(50),

OFICIO VARCHAR2(50),

DIR NUMBER(4),

FECHA_ALT DATE ,

SALARIO NUMBER(8,2),

COMISION NUMBER(8,2),

DEPT_NO NUMBER(2)


/*constraint*/

);

/*


EL CODIGO DE DEPARTAMENTO TIENE QUE ESTAR ENTRE 0 Y 99
EL NOMBRE TIENE QUE IR CON MAY SCULAS
LA LOCALIDAD SOLO PUEDE TENER VALORES SEVILLA,MADRID,BARCELONA Y BILBAO

///////////////////////////////////////////////////////////////////////////

DIR ("DIRECTOR") REPRESENTA UNA REFERENCIA REFLEXIVA 
EL CODIGO DE EMPLEADO TIENE QUE ESTAR ENTRE 1000 Y 9999
EL APELLIDO TIENE QUE IR CON MAYÚSCULAS
EL OFICIO  SOLO PUEDE TENER VALORES PRESIDENTE, ANALISTA, EMPLEADO,DIRECTOR Y VENDEDOR
EL SALARIO TIENE QUE SER POSITIVO
LA FECHA SI NO SE PONE TENDRÁ  EL VALOR POR DEFECTO DE LA FECHA DEL MOMENTO EN EL QUE SE HACE LA INSERCIÓN
EL SALARIO SI NO SE PONE UN VALOR SE INSERTARÁ EL SALARIO POR DEFECTO 1080

*/