CREATE TABLE DEPART(
DEPT_NO NUMBER(2) NOT NULL,
DNOMBRE VARCHAR2(50) NOT NULL,
LOC VARCHAR2(50) NOT NULL,

CONSTRAINT PK_DEPT_NO PRIMARY KEY (DEPT_NO),
CONSTRAINT LOCALIDAD CHECK (LOC IN ('SEVILLA','MADRID','BARCELONA','BILBAO')),
CONSTRAINT DNOMBRE_MAYUS CHECK (DNOMBRE = UPPER(DNOMBRE)),
CONSTRAINT ENTRE_DEPT CHECK (DEPT_NO BETWEEN 0 AND 99)
);


CREATE TABLE EMPLE(
EMP_NO     NUMBER(4) NOT NULL,
APELLIDO   VARCHAR2(50) NOT NULL,
OFICIO     VARCHAR2(50) NOT NULL,
DIR        NUMBER(4),
FECHA_ALT  DATE DEFAULT SYSDATE NOT NULL,
SALARIO    NUMBER(8,2) DEFAULT 1080 NOT NULL,
COMISION   NUMBER(8,2),
DEPT_NO    NUMBER(2) NOT NULL,

CONSTRAINT PK_EMP_NO PRIMARY KEY (EMP_NO),
CONSTRAINT ENTRE_EMP CHECK (EMP_NO BETWEEN 1000 AND 9999),
CONSTRAINT APELLIDO_MAYUS CHECK(APELLIDO = UPPER(APELLIDO)),
CONSTRAINT OFICIO_CHECK CHECK (OFICIO IN ('PRESIDENTE','ANALISTA','EMPLEADO','DIRECTOR','VENDEDOR')),
CONSTRAINT SALARIO_POSITIVO CHECK (SALARIO >= 0),
CONSTRAINT FK_DEPT_NO FOREIGN KEY (DEPT_NO) REFERENCES DEPART(DEPT_NO),
CONSTRAINT FK_DIR FOREIGN KEY (DIR) REFERENCES EMPLE(EMP_NO)
);




/*

///////////////////////////////////////////////////////////////////////////

EL CODIGO DE DEPARTAMENTO TIENE QUE ESTAR ENTRE 0 Y 99
EL NOMBRE TIENE QUE IR CON MAY SCULAS
LA LOCALIDAD SOLO PUEDE TENER VALORES SEVILLA,MADRID,BARCELONA Y BILBAO

///////////////////////////////////////////////////////////////////////////

DIR ("DIRECTOR") REPRESENTA UNA REFERENCIA REFLEXIVA 
EL CODIGO DE EMPLEADO TIENE QUE ESTAR ENTRE 1000 Y 9999
EL APELLIDO TIENE QUE IR CON MAYÚSCULAS
EL OFICIO  SOLO PUEDE TENER VALORES PRESIDENTE, ANALISTA, EMPLEADO,DIRECTOR Y VENDEDOR
EL SALARIO TIENE QUE SER POSITIVO
LA FECHA SI NO SE PONE TENDRÁ  EL VALOR POR DEFECTO DE LA FECHA DEL MOMENTO EN EL QUE SE HACE LA INSERCIÓN
EL SALARIO SI NO SE PONE UN VALOR SE INSERTARÁ EL SALARIO POR DEFECTO 1080

*/